# -*- coding: utf-8 -*-

"""
    onfonmediasmsgateway

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from onfonmediasmsgateway.api_helper import APIHelper


class Configuration(object):

    """A class used for configuring the SDK by a user.

    This class need not be instantiated and all properties and methods
    are accessible without instance creation.

    """

    # Set the array parameter serialization method
    # (allowed: indexed, unindexed, plain, csv, tsv, psv)
    array_serialization = "indexed"

    # The base Uri for API calls
    base_uri = 'https://api.onfonmedia.co.ke/v1/sms'

    # Transport Layer ApiKey
    apikey = 'TRANSPORT_LAYER_APIKEY'

    # Message Layer ApiKey used for authentication purpose and pass this
    # parameter in URL encoded format.
    api_key = 'MESSAGE_LAYER_APIKEY'

    # Message Layer ClientId used for authentication purpose and pass this
    # parameter in URL encoded format.
    client_id = 'MESSAGE_LAYER_APIKEY'

