# -*- coding: utf-8 -*-

"""
    onfonmediasmsgateway

    This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
"""

from onfonmediasmsgateway.decorators import lazy_property
from onfonmediasmsgateway.configuration import Configuration
from onfonmediasmsgateway.controllers.account_controller import AccountController
from onfonmediasmsgateway.controllers.template_controller import TemplateController


class OnfonmediasmsgatewayClient(object):

    config = Configuration

    @lazy_property
    def account(self):
        return AccountController()

    @lazy_property
    def template(self):
        return TemplateController()


    def __init__(self,
                 apikey='TRANSPORT_LAYER_APIKEY',
                 api_key='MESSAGE_LAYER_APIKEY',
                 client_id='MESSAGE_LAYER_APIKEY'):
        if apikey is not None:
            Configuration.apikey = apikey
        if api_key is not None:
            Configuration.api_key = api_key
        if client_id is not None:
            Configuration.client_id = client_id

